name: backend_test
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  args: ^2.3.0
  dart_code_metrics: ^5.7.4
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  content_length_validator: ^1.1.1
  shelf_helmet: ^2.0.0
  shelf_cors_headers: ^0.1.5
  image_compression: ^1.0.4

dev_dependencies:
  shelf_hotreload: ^1.4.0
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
